In [1]:
# Importação das bibliotecas
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

In [31]:
# Carregando a base de dados Varejo
df = pd.read_csv(r"C:\Users\Usuário\Documents\Miniprojeto_JessicaFinardi_DadosV2\Dados\Base_Varejo.csv", sep=";")

# Exibindo as 5 primeiras linhas.
df.head(5)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [51]:
# Exibindo informações
print('\n===== INFORMAÇÕES GERAIS =====')
print(f"O dataset tem {df.shape[0]} linhas e {df.shape[1]} colunas")
print()
print('\nNomes das colunas:')
print(df.columns)
print()
print('\nTipos de dados das colunas:')
print(df.dtypes)

===== INFORMAÇÕES GERAIS =====
O dataset tem 830000 linhas e 14 colunas


Nomes das colunas:
Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='str')


Tipos de dados das colunas:
DATA           datetime64[us]
CO_ID                   int64
CL_ID                   int64
CL_GENERO                 str
CL_EC                   int64
CL_FHL                  int64
CL_SEG                    str
PR_ID                   int64
PR_CAT                    str
PR_NOME                   str
Unnamed: 10           float64
Unnamed: 11           float64
Unnamed: 12           float64
Unnamed: 13           float64
dtype: object

In [32]:
# Contagem de nulos por coluna
nulos = df.isnull().sum()
print("\nQuantidade de valores nulos por coluna:\n")
print(nulos)

Quantidade de valores nulos por coluna:

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [50]:
# Quantidade de linhas duplicadas
duplicadas = df.duplicated().sum()
print(f"\nQuantidade de linhas duplicadas: {duplicadas}\n")

# Visualização de linhas duplicadas
#df[df.duplicated()]
df[df.duplicated(subset=['CL_ID', 'PR_ID'])]
df[df.duplicated(subset=['CO_ID', 'PR_ID'], keep=False)]

Quantidade de linhas duplicadas: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,2019-01-02,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,2019-01-02,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,2019-01-02,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,2019-01-02,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,2019-01-02,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,NaT,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829992,NaT,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN
829995,NaT,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,NaT,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,NaT,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN

In [ ]:
# Verificando datas inválidas
df["DATA"] = pd.to_datetime(df["DATA"], errors="coerce")
datas_invalidas = df[df["DATA"].isnull()]
print("\nDatas inválidas:\n")
print(datas_invalidas)

In [ ]:
# Criando uma cópia do database
df_copia = df.copy()

In [ ]:
# Removendo colunas Unnamed: 10, Unnamed: 11, Unnamed: 12 e Unnamed: 13. 
df_remove_coluna = df.dropna(axis=1, how='all')
print(df_remove_coluna)

             DATA   CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID  \
0      2019-01-02    1000    534         M      4       1      C     67
1      2019-01-02    1000    534         M      4       1      C     70
2      2019-01-02    1000    534         M      4       1      C    178
3      2019-01-02    1000    534         M      4       1      C      4
4      2019-01-02    1000    534         M      4       1      C    175
...           ...     ...    ...       ...    ...     ...    ...    ...
829995        NaT  919822    155         F      2       0      B    183
829996        NaT  919822    155         F      2       0      B     56
829997        NaT  919822    155         F      2       0      B    227
829998        NaT  919822    155         F      2       0      B    214
829999        NaT  919822    155         F      2       0      B     59

           PR_CAT               PR_NOME  Unnamed: 10  Unnamed: 11  \
0         BEBIDAS  REFRIGERANTE GUARANA          NaN          NaN
1         BEBIDAS   REFRIGERANTE OUTROS          NaN          NaN
2         HIGIENE       LENCO UMEDECIDO          NaN          NaN
3       ALIMENTOS               ABACAXI          NaN          NaN
4         LIMPEZA     LIMPADOR MULTIUSO          NaN          NaN
...           ...                   ...          ...          ...
829995  ALIMENTOS               KETCHUP          NaN          NaN
829996  ALIMENTOS      QUEIJO MUSSARELA          NaN          NaN
829997  ALIMENTOS                 ARROZ          NaN          NaN
829998  ALIMENTOS                CEBOLA          NaN          NaN
829999  ALIMENTOS            SALGADINHO          NaN          NaN

        Unnamed: 12  Unnamed: 13
0               NaN          NaN
1               NaN          NaN
2               NaN          NaN
3               NaN          NaN
4               NaN          NaN
...             ...          ...
829995          NaN          NaN
829996          NaN          NaN
829997          NaN          NaN
829998          NaN          NaN
829999          NaN          NaN

[830000 rows x 14 columns]